apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: labwordpress
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi