apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: labwordpress
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi