apiVersion: v1
kind: Service
metadata:
  namespace: labwordpress
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3308
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None